mogodb:
  image: 'mongo'
  volumes:
      - ../database/files:/data/db
  ports:
      - 27017:27017
myapp:
  image: 'laravel:latest'
  links:
    - mogodb:mogodb
  ports:
    - 80:80
  volumes:
    - ../:/var/www/html/laravel/

